export * from './config'
export * from './useCourseDetails'
export * from './useCourseFeedback'
export * from './useDegreeCourseGroups'
export * from './useDegreeCourses'
export * from './useFaculties'
export * from './useSubmitFeedback'
export * from './useUrlNavigation'
