// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/terms" | "/privacy";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/terms" | "/privacy";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
};