services:
  website-ssr:
    image: uni-feedback-website-ssr:latest
    build:
      context: ../../  # Build from monorepo root
      dockerfile: apps/website-ssr/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker  # Use Docker-specific environment file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s