export * from './queries'
export * from './useAuth'
export * from './useCountdown'
export * from './useDebounce'
export * from './useFeedbackDraft'
export * from './useGiveawayDisplayMode'
export * from './useLang'
export * from './useLastVisitedPath'
export * from './useLocalStorage'
// @deprecated - Use useOtpAuth instead. Magic links are being replaced by OTP authentication.
export * from './useMagicLinkAuth'
export * from './useOtpAuth'
export * from './usePreselectedFacultyDegree'
export * from './useReferralShare'
