services:
  db:
    image: postgres:15
    restart: always
    container_name: uni-feedback-db
    environment:
      POSTGRES_DB: uni-feedback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - uni_feedback_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uni_feedback_postgres_data: