name = "meic-feedback"
main = "index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
account_id = "6775eddc96fc027d1dca7762dfd44efa"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
WORKER_ENV = "prod"
DASHBOARD_URL = "admin.uni-feedback.com"
# DATABASE_URL should be set as a secret using: wrangler secret put DATABASE_URL

