name = "meic-feedback"
main = "index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
account_id = "6775eddc96fc027d1dca7762dfd44efa"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
WORKER_ENV = "prod"


[[d1_databases]]
binding = "DB"
database_name = "meic-feedback"
database_id = "31aa2a7b-6eb4-4639-8588-643e0cc1098b"
migrations_dir = "src/db/migrations"
